# Generated by Django 5.1.1 on 2024-12-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория операции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Finance_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Доход', 'Income'), ('Расход', 'Expenses'), ('Не выбрано', 'Non')], default='Не выбрано', max_length=10, verbose_name='Тип операции')),
                ('operation_name', models.CharField(max_length=255, verbose_name='Название операции')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('amount', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='finance_site.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Операции',
                'verbose_name_plural': 'Операции',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='finance_sit_time_cr_c66816_idx')],
            },
        ),
    ]
