# Generated by Django 5.1.1 on 2024-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_site', '0005_remove_category_author_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_site',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='finance_site',
            name='operation_type',
            field=models.CharField(choices=[('0', 'Доход'), ('1', 'Расход')], default=1, max_length=10, verbose_name='Тип операции'),
        ),
    ]
