# Generated by Django 5.1.1 on 2024-12-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_site', '0006_alter_finance_site_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_site',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='finance_site.category', verbose_name='Категории'),
        ),
    ]
